- type: entity
  name: Federation Military Credit
  parent: BaseItem
  id: FederationMilitaryCredit
  suffix: 20 TC
  description: A token awarded to TSF personnel for turning in contraband. It can be exchanged in an TSFMC uplink device for a variety of law enforcement tools.
  components:
  - type: Sprite
    sprite: _NF/Objects/Specific/Security/frontieruplinkcoin.rsi
    state: frontieruplinkcoin
  - type: Item
    sprite: _NF/Objects/Specific/Security/frontieruplinkcoin.rsi
    size: Tiny
  - type: Stack
    count: 20
    stackType: FederationMilitaryCredit
  - type: StaticPrice
    price: 0
  - type: StackPrice
    price: 200
  - type: Currency
    price:
      FederationMilitaryCredit: 1

- type: entity
  parent: FederationMilitaryCredit
  id: FederationMilitaryCredit1
  suffix: 1 TC
  components:
  - type: Stack
    count: 1

- type: entity
  parent: FederationMilitaryCredit
  id: FederationMilitaryCredit5
  suffix: 5 TC
  components:
  - type: Stack
    count: 5

- type: entity
  parent: FederationMilitaryCredit
  id: FederationMilitaryCredit10
  suffix: 10 TC
  components:
  - type: Stack
    count: 10

# Uplinks
- type: entity
  parent: [ BaseItem, StorePresetSecurityUplink ]
  id: BaseSecurityUplinkRadio
  name: TSFMC uplink
  description: Retro looking old radio...
  suffix: Empty
  categories: [ HideSpawnMenu ]
  components:
  - type: Sprite
    sprite: Objects/Devices/communication.rsi
    layers:
    - state: old-radio
  - type: Item
    sprite: Objects/Devices/communication.rsi
    heldPrefix: old-radio
  - type: UserInterface
    interfaces:
      enum.StoreUiKey.Key:
        type: StoreBoundUserInterface
  - type: ActivatableUI
    key: enum.StoreUiKey.Key
  - type: Tag
    tags:
    - SecurityUplink

- type: entity
  parent: BaseSecurityUplinkRadio
  id: BaseSecurityUplinkRadioDebug
  suffix: Security, DEBUG
  components:
  - type: Store
    balance:
      FederationMilitaryCredit: 99999

- type: entity
  parent: BaseSecurityUplinkRadio
  id: BaseSecurityUplinkRadioSheriff
  suffix: Colonel 20
  components:
  - type: Store
    balance:
      FederationMilitaryCredit: 20

- type: entity
  parent: BaseSecurityUplinkRadio
  id: BaseSecurityUplinkRadioOfficer
  suffix: Officer 15
  components:
  - type: Store
    balance:
      FederationMilitaryCredit: 15

#Mono

- type: entity
  parent: BaseSecurityUplinkRadio
  id: BaseSecurityUplinkRadioDeputy
  suffix: Deputy 10
  components:
  - type: Store
    balance:
      FederationMilitaryCredit: 10

#Mono End

- type: entity
  name: TSFMC deployable barrier
  id: NfsdDeployableBarrier
  description: A deployable barrier. Swipe your ID card to lock/unlock it.
  parent: DeployableBarrier
  components:
  - type: Sprite
    sprite: _NF/Objects/Specific/Security/nfsdbarrier.rsi
    layers:
    - state: idle
    - state: locked
      map: ["enum.LockVisualLayers.Lock"]
